// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnmbwccznpikmkrzjoin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubWJ3Y2N6bnBpa21rcnpqb2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODYyMjYsImV4cCI6MjA2Nzk2MjIyNn0.KYtvVc1aggDuO-xxgKpxFE4yRt95gl3gE88fD8mDvHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});